@echo off
rem snake_std 标准实现冒烟验证：自检（18 组）+ 3 代小规模端到端 + 三观测环境 + 研究选项
cd /d "%~dp0"
if not defined PY set PY=python

echo [1/8] selfcheck（适应度/CRN/稀疏等价/观测等价/激素/鲁棒/池/固定地图/K帧消融/w_ii自连/E泄漏积分器/w_ee）...
%PY% -X utf8 -u snake_std.py --selfcheck  2>&1 | tee logs\snake_std_selfcheck.log
echo [2/8] smoke 默认（=16b 行为，obs40）...
%PY% -X utf8 -u snake_std.py --smoke --name sm_default  2>&1 | tee logs\snake_std_smoke_default.log
echo [3/8] smoke --obs 32ego ...
%PY% -X utf8 -u snake_std.py --smoke --name sm_ego32 --obs 32ego  2>&1 | tee logs\snake_std_smoke_ego32.log
echo [4/8] smoke --obs 32proj ...
%PY% -X utf8 -u snake_std.py --smoke --name sm_proj32 --obs 32proj  2>&1 | tee logs\snake_std_smoke_proj32.log
echo [5/8] smoke 激素+轮换 ...
%PY% -X utf8 -u snake_std.py --smoke --name sm_hormone --train-hormone --cycle-pattern G1,G2,G3  2>&1 | tee logs\snake_std_smoke_hormone.log
echo [6/8] smoke K帧首帧输入+尾帧读出（test17）...
%PY% -X utf8 -u snake_std.py --smoke --name sm_kft --kframe-input first --kframe-read tail  2>&1 | tee logs\snake_std_smoke_kft.log
echo [7/8] smoke w_ii+自连（test17A）...
%PY% -X utf8 -u snake_std.py --smoke --name sm_a2 --allow-self-conn --train-wii  2>&1 | tee logs\snake_std_smoke_a2.log
echo [8/8] smoke E泄漏积分器+w_ii+w_ee（test17B'）...
%PY% -X utf8 -u snake_std.py --smoke --name sm_b2 --euler-leak --train-wii --train-wee  2>&1 | tee logs\snake_std_smoke_b2.log
pause
